[package]
name = "cpuinfo"
version = "0.1.0"
authors = ["losfair <zhy20000919@hotmail.com>"]

[lib]
name = "cpuinfo"
crate-type = ["cdylib"]

[dependencies]
ia = { path = "../.." }
futures-await = "0.1"
