language: rust
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install xz llvm@3.8; fi
script:
  - find / | grep -i llvm 2> /dev/null
  - cargo build --release --verbose
  - cargo test --release --verbose
  - ls target/release
  - mkdir dist
  - cp target/release/libice_core.* dist/
  - tar c dist | xz -9 > $DEPLOY_FILE
matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - libedit2
            - libedit-dev
      env: DEPLOY_FILE=ice_core_linux.tar.xz
    - os: osx
      osx_image: xcode7.3
      env: DEPLOY_FILE=ice_core_macos.tar.xz
deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file: "$DEPLOY_FILE"
  skip_cleanup: true
  on:
    tags: true
