[package]
name = "ice_core"
version = "0.3.1"
authors = ["losfair <zhy20000919@hotmail.com>"]

[lib]
name = "ice_core"
crate-type = ["cdylib"]

[features]
use_cervus = ["cervus"]

[dependencies]
hyper = "0.11"
futures = "*"
tokio-core = "*"
tokio-io = "*"
uuid = { version = "0.4", features = ["v4"] }
chrono = "0.4.0"
tera = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
ansi_term = "*"
etag = "*"
sequence_trie = "*"
byteorder = "*"
lazy_static = "*"
cervus = { version = "0.1", optional = true }
