[package]
name = "ice_core"
version = "0.3.2"
authors = ["losfair <zhy20000919@hotmail.com>"]
description = "High performance Web engine"
license = "LGPL-3.0"
repository = "https://github.com/losfair/IceCore"

[lib]
name = "ice_core"
crate-type = ["cdylib"]

[dependencies]
hyper = "0.11"
futures = "*"
tokio-core = "*"
tokio-io = "*"
uuid = { version = "0.4", features = ["v4"] }
chrono = "0.4.0"
tera = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
ansi_term = "*"
etag = "*"
sequence_trie = "*"
byteorder = "*"
lazy_static = "*"
cervus = "0.2"
