[package]
name = "ice_core"
version = "0.1.5"
authors = ["losfair <zhy20000919@hotmail.com>"]
links = "ice_glue ice_internal_prefix_tree"
build = "build.rs"

[lib]
name = "ice_core"
crate-type = ["dylib", "staticlib"]

[dependencies]
hyper = "0.11"
futures = "*"
tokio-core = "*"
tokio-io = "*"
uuid = { version = "0.4", features = ["v4"] }
chrono = "0.4.0"
tera = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
ansi_term = "*"
etag = "*"
sequence_trie = "*"

[build-dependencies]
gcc = "*"
