[package]
name = "ice_core"
version = "0.1.0"
authors = ["losfair <zhy20000919@hotmail.com>"]
links = "ice_glue ice_internal_prefix_tree"
build = "build.rs"

[lib]
name = "ice_core"
crate-type = ["dylib"]

[dependencies]
hyper = "0.11"
futures = "*"

[build-dependencies]
gcc = "*"
